### ISSUE TITLE
Align command line to be the same as JVM mode

### ISSUE THREAD

**Issue by ryanemerson** [infinispan/infinispan-quarkus#110]
Runtime replacement of properties in the config fails with:

```java
2022-09-22 09:17:08,143 WARN  [org.inf.com.uti.StringPropertyReplacer] (main) ISPN000901: Property infinispan.bind.address could not be replaced as intended!
2022-09-22 09:17:08,145 ERROR [io.qua.run.Application] (main) Failed to start application (with profile prod): org.infinispan.commons.CacheConfigurationException: ISPN080033: Cannot find a network address which matches the supplied configuration
	at org.infinispan.server.configuration.ServerConfigurationParser.parseInterface(ServerConfigurationParser.java:212)
	at org.infinispan.server.configuration.ServerConfigurationParser.parseInterfaces(ServerConfigurationParser.java:199)
	at org.infinispan.server.configuration.ServerConfigurationParser.parseServerElements(ServerConfigurationParser.java:118)
	at org.infinispan.server.configuration.ServerConfigurationParser.readElement(ServerConfigurationParser.java:104)
	at org.infinispan.configuration.parsing.ParserRegistry.parseElement(ParserRegistry.java:209)
	at org.infinispan.configuration.parsing.ConfigurationBuilderHolder.handleAnyElement(ConfigurationBuilderHolder.java:139)
	at org.infinispan.commons.configuration.io.AbstractConfigurationReader.handleAny(AbstractConfigurationReader.java:57)
	at org.infinispan.configuration.parsing.Parser.readElement(Parser.java:99)
	at org.infinispan.configuration.parsing.ParserRegistry.parseElement(ParserRegistry.java:209)
	at org.infinispan.configuration.parsing.ParserRegistry.parse(ParserRegistry.java:187)
	at org.infinispan.configuration.parsing.ParserRegistry.parse(ParserRegistry.java:175)
	at org.infinispan.configuration.parsing.ParserRegistry.parse(ParserRegistry.java:169)
	at org.infinispan.server.Server.parseConfiguration(Server.java:319)
	at org.infinispan.server.Server.<init>(Server.java:234)
	at org.infinispan.server.Server.<init>(Server.java:238)
	at org.infinispan.quarkus.server.runtime.InfinispanServerProducer.server(InfinispanServerProducer.java:49)
	at org.infinispan.quarkus.server.runtime.InfinispanServerProducer_ProducerMethod_server_571276351519ba727e1410402ad4516addb1c6ca_Bean.create(Unknown Source)
	at org.infinispan.quarkus.server.runtime.InfinispanServerProducer_ProducerMethod_server_571276351519ba727e1410402ad4516addb1c6ca_Bean.get(Unknown Source)
	at org.infinispan.quarkus.server.runtime.InfinispanServerProducer_ProducerMethod_server_571276351519ba727e1410402ad4516addb1c6ca_Bean.get(Unknown Source)
	at org.infininspan.quarkus.server.ServerResource_Bean.create(Unknown Source)
	at org.infininspan.quarkus.server.ServerResource_Bean.get(Unknown Source)
	at org.infininspan.quarkus.server.ServerResource_Bean.get(Unknown Source)
	at org.infininspan.quarkus.server.ServerResource_Observer_onStart_da126b23a7ea25adb73fb68c8f927996fd3e1211.notify(Unknown Source)
	at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:323)
	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:305)
	at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:73)
	at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:130)
	at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:99)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(Unknown Source)
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:103)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:120)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	Suppressed: java.net.UnknownHostException: ${infinispan.bind.address}: Name or service not known
		at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST_UnknownHostException_constructor_f8848c751ae5754fccea1b6f6ce5ccd75f1459a6(JNIJavaCallWrappers.java:0)
		at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java)
		at java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:929)
		at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1519)
		at java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:848)
		at java.net.InetAddress.getAllByName0(InetAddress.java:1509)
		at java.net.InetAddress.getAllByName(InetAddress.java:1368)
		at java.net.InetAddress.getAllByName(InetAddress.java:1302)
		at java.net.InetAddress.getByName(InetAddress.java:1252)
		at org.infinispan.server.network.NetworkAddress.inetAddress(NetworkAddress.java:145)
		at org.infinispan.server.network.NetworkAddress.fromString(NetworkAddress.java:101)
		at org.infinispan.server.configuration.InterfaceConfigurationBuilder.createNetworkAddress(InterfaceConfigurationBuilder.java:43)
		at org.infinispan.server.configuration.InterfaceConfigurationBuilder.address(InterfaceConfigurationBuilder.java:23)
		at org.infinispan.server.configuration.ServerConfigurationParser.parseInterface(ServerConfigurationParser.java:221)
		... 36 more
```

Xml configuration snippet causing the issue:

```xml
<inet-address value="${infinispan.bind.address}"/>
```

**Comment by wburns** [comment]
This is caused because the code that starts the Server doesn't utilize the Bootstrap class to pull in all the command line arguments. Now that Quarkus actually supports command line applications, we probably need to change to that and utilize the Bootstrap class.

**Comment by wburns** [comment]
Updating this Issue to instead convert the Infinispan Quarkus server to use command mode of Quarkus and support same command line arguments as the JVM mode Infinispan Server. This will allow for a drop in. A user can simply copy/paste the native binary into the extracted server zip and use it instead of the server launcher.

**Comment by wburns** [comment]
Should be fixed. Any additional failures will be a new issue.
