### ISSUE TITLE
14.0.1 Native build compilation error

### ISSUE THREAD

**Issue by wburns** [infinispan/infinispan-quarkus#112]
We now receive the following build error:

```
Fatal error: org.graalvm.compiler.debug.GraalError: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: No instances of java.net.Inet6Address are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use --trace-object-instantiation=java.net.Inet6Address.
	at com.oracle.graal.pointsto.util.AnalysisFuture.setException(AnalysisFuture.java:49)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:269)
	at com.oracle.graal.pointsto.util.AnalysisFuture.ensureDone(AnalysisFuture.java:63)
	at com.oracle.graal.pointsto.heap.ImageHeapScanner.lambda$postTask$9(ImageHeapScanner.java:611)
	at com.oracle.graal.pointsto.util.CompletionExecutor.executeCommand(CompletionExecutor.java:193)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$executeService$0(CompletionExecutor.java:177)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: No instances of java.net.Inet6Address are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use --trace-object-instantiation=java.net.Inet6Address.
	at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.checkImageHeapInstance(ClassInitializationFeature.java:135)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.replaceObject(AnalysisUniverse.java:582)
	at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.replaceObject(AnalysisConstantReflectionProvider.java:257)
	at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.interceptValue(AnalysisConstantReflectionProvider.java:228)
	at com.oracle.svm.hosted.heap.SVMImageHeapScanner.transformFieldValue(SVMImageHeapScanner.java:126)
	at com.oracle.graal.pointsto.heap.ImageHeapScanner.onFieldValueReachable(ImageHeapScanner.java:331)
	at com.oracle.graal.pointsto.heap.ImageHeapScanner.lambda$createImageHeapObject$3(ImageHeapScanner.java:272)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 10 more
```

When tracing the initialization of Inet6Address it shows the following:

```
Fatal error: org.graalvm.compiler.debug.GraalError: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: No instances of java.net.Inet6Address are allowed in the image heap as this class should be initialized at image runtime. Object has been initialized by the org.infinispan.server.hotrod.MultiHomedServerAddress$InetAddressWithNetMask class initializer with a trace: 
 	at java.net.Inet6Address.<init>(Inet6Address.java:386)
	at java.net.InetAddress.getByAddress(InetAddress.java:1211)
	at java.net.InetAddress.getByAddress(InetAddress.java:1585)
	at org.infinispan.server.hotrod.MultiHomedServerAddress$InetAddressWithNetMask.<init>(MultiHomedServerAddress.java:187)
	at org.infinispan.server.hotrod.MultiHomedServerAddress$InetAddressWithNetMask.<clinit>(MultiHomedServerAddress.java:156)
.  To fix the issue mark java.net.Inet6Address for build-time initialization with --initialize-at-build-time=java.net.Inet6Address or use the the information from the trace to find the culprit and --initialize-at-run-time=<culprit> to prevent its instantiation.
```

It appears to be due to https://github.com/infinispan/infinispan/commit/f3f4e8ce95938c6ff08c9c2e46ac887cd9f991e6#diff-40d33a12a233e59f94f3684cfe38724349bc3350619d8613d25424a8c94e8822R142. We need to delay initialization of the fields until runtime.

**Comment by wburns** [comment]
The new error appears to complain about `java.util.Arrays$ArrayList` which makes no sense. I also generate quarkus reports to show used classes and it is present

```
/home/wburns/RedHat/infinispan-quarkus/integration-tests/embedded/target/infinispan-quarkus-integration-test-embedded-14.0.0-SNAPSHOT-native-image-source-jar/reports
[wburns@wburns reports]$ grep Arrays\\\$ArrayList used_classes* -H
used_classes_infinispan-quarkus-integration-test-embedded-14.0.0-SNAPSHOT-runner_20221005_143754.txt:java.util.Arrays$ArrayList
```

**Comment by wburns** [comment]
However doing a text search in the compiled binary does not have the string `java.util.Arrays$ArrayList`. Still investigating.

**Comment by wburns** [comment]
It looks like a change, possible regression in Quarkus. If I downgrade back to Quarkus 2.11.0.Final it works. Going to look and compare further.

**Comment by wburns** [comment]
It appears to be a regression with 2.13.1. If I revert to 2.13.0 it seems to pass.

**Comment by wburns** [comment]
One possible change may be https://github.com/quarkusio/quarkus/commit/02f206b2785c4a85484b0b4d5090409f7d0fbb98, but I would need to dig further.
