### ISSUE TITLE
Unable to use JGroups DNS_PING protocol

### ISSUE THREAD

**Issue by ryanemerson** [infinispan/infinispan-quarkus#116]
We rely on DNS_PING in k8s environments to discover cluster members. However, the current  (14.0.1.Final) native image does not have JNDI enabled so this always fails with the following logs:

```
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2022-10-18 10:49:36,631 INFO  [io.quarkus] (main) infinispan-quarkus-server-runner 14.0.1.Final native (powered by Quarkus 2.13.0.Final) started in 0.010s. 
2022-10-18 10:49:36,632 INFO  [io.quarkus] (main) Profile prod activated. 
2022-10-18 10:49:36,632 INFO  [io.quarkus] (main) Installed features: [cdi, infinispan-embedded, infinispan-server]
2022-10-18 10:49:36,632 INFO  [BOOT] (main) JVM Substrate VM Oracle Corporation GraalVM 22.1.0 Java 11 CE
2022-10-18 10:49:36,632 INFO  [BOOT] (main) JVM arguments = [-Dinfinispan.server.home.path=/opt/infinispan, --bind-address=0.0.0.0, -l, /opt/infinispan/server/conf/operator/log4j.xml, -c, operator/infinispan-base.xml, -c, operator/infinispan-admin.xml]
2022-10-18 10:49:36,632 INFO  [BOOT] (main) PID = 47
2022-10-18 10:49:36,632 INFO  [org.inf.SERVER] (main) ISPN080000: Infinispan Server 14.0.1.Final starting
2022-10-18 10:49:36,632 INFO  [org.inf.SERVER] (main) ISPN080017: Server configuration: operator/infinispan-base.xml
2022-10-18 10:49:36,632 INFO  [org.inf.SERVER] (main) ISPN080017: Server configuration: operator/infinispan-admin.xml
2022-10-18 10:49:36,632 INFO  [org.inf.SERVER] (main) ISPN080032: Logging configuration: /opt/infinispan/server/conf/operator/log4j.xml
2022-10-18 10:49:36,639 WARN  [org.inf.SERVER] (main) ISPN080059: No script engines are available
2022-10-18 10:49:36,642 INFO  [org.inf.CONTAINER] (main) ISPN000556: Starting user marshaller 'org.infinispan.commons.marshall.ImmutableProtoStreamMarshaller'
2022-10-18 10:49:36,651 INFO  [org.inf.CLUSTER] (main) ISPN000078: Starting JGroups channel `test-base-functionality` with stack `image-tcp`
2022-10-18 10:49:36,656 ERROR [org.inf.CONFIG] (main) ISPN000660: DefaultCacheManager start failed, stopping any running components: org.infinispan.commons.CacheConfigurationException: ISPN000541: Error while trying to create a channel using the specified configuration '[TCP(bundler.max_size=64000, sock_conn_timeout=300, thread_pool.keep_alive_time=60000, port_range=0, diag.enabled=false, bind_port=7800, thread_naming_pattern=pl, thread_pool.thread_dumps_threshold=10000, send_buf_size=640k, thread_pool.max_threads=200, bundler_type=transfer-queue, bind_addr=SITE_LOCAL, thread_pool.min_threads=0), RED(), MPING(ip_ttl=2, mcast_port=46655, mcast_addr=239.6.7.8, num_discovery_runs=3), MERGE3(max_interval=30000, min_interval=10000), FD_SOCK2(offset=50000), FD_ALL3(), VERIFY_SUSPECT2(timeout=1000), pbcast.NAKACK2(xmit_table_num_rows=50, use_mcast_xmit=false, xmit_table_msgs_per_row=1024, xmit_table_max_compaction_time=30000, xmit_interval=200, resend_last_seqno=true), UNICAST3(conn_close_timeout=5000, xmit_interval=200, xmit_table_num_rows=50, xmit_table_msgs_per_row=1024, xmit_table_max_compaction_time=30000), pbcast.STABLE(desired_avg_gossip=5000, max_bytes=1M), pbcast.GMS(join_timeout=2000, print_local_addr=false), UFC(min_threshold=0.40, max_credits=4m), MFC(min_threshold=0.40, max_credits=4m), FRAG4(frag_size=60000), dns.DNS_PING(dns_record_type=A, dns_query=test-base-functionality-ping.namespace-for-testing.svc.cluster.local)]'
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.channelFromConfigurator(JGroupsTransport.java:776)
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.buildChannel(JGroupsTransport.java:745)
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.initChannel(JGroupsTransport.java:510)
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.start(JGroupsTransport.java:491)
	at org.infinispan.remoting.transport.jgroups.CorePackageImpl$1.start(CorePackageImpl.java:42)
	at org.infinispan.remoting.transport.jgroups.CorePackageImpl$1.start(CorePackageImpl.java:27)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.invokeStart(BasicComponentRegistryImpl.java:617)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:608)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:577)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:808)
	at org.infinispan.metrics.impl.MetricsCollector.start(MetricsCollector.java:76)
	at org.infinispan.metrics.impl.CorePackageImpl$1.start(CorePackageImpl.java:41)
	at org.infinispan.metrics.impl.CorePackageImpl$1.start(CorePackageImpl.java:34)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.invokeStart(BasicComponentRegistryImpl.java:617)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:608)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:577)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:808)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startDependencies(BasicComponentRegistryImpl.java:635)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:599)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:577)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:808)
	at org.infinispan.factories.AbstractComponentRegistry.internalStart(AbstractComponentRegistry.java:357)
	at org.infinispan.factories.AbstractComponentRegistry.start(AbstractComponentRegistry.java:250)
	at org.infinispan.manager.DefaultCacheManager.internalStart(DefaultCacheManager.java:774)
	at org.infinispan.manager.DefaultCacheManager.start(DefaultCacheManager.java:742)
	at org.infinispan.server.SecurityActions.lambda$startCacheManager$1(SecurityActions.java:68)
	at org.infinispan.security.Security.doPrivileged(Security.java:56)
	at org.infinispan.server.SecurityActions.doPrivileged(SecurityActions.java:40)
	at org.infinispan.server.SecurityActions.startCacheManager(SecurityActions.java:71)
	at org.infinispan.server.Server.run(Server.java:408)
	at org.infinispan.server.Bootstrap.runInternal(Bootstrap.java:173)
	at org.infinispan.server.tool.Main.run(Main.java:98)
	at org.infinispan.server.Bootstrap.main(Bootstrap.java:56)
	at org.infininspan.quarkus.server.InfinispanQuarkusServer.run(InfinispanQuarkusServer.java:13)
	at org.infininspan.quarkus.server.InfinispanQuarkusServer_ClientProxy.run(Unknown Source)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:131)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:69)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
Caused by: javax.naming.NamingException: JNDI has been disabled, enable it with quarkus.naming.enable-jndi=true
	at io.quarkus.runtime.naming.DisabledInitialContext.init(DisabledInitialContext.java:210)
	at javax.naming.InitialContext.<init>(InitialContext.java:208)
	at javax.naming.directory.InitialDirContext.<init>(InitialDirContext.java:101)
	at javax.naming.ldap.InitialLdapContext.<init>(InitialLdapContext.java:102)
	at io.quarkus.runtime.naming.DisabledInitialContext.<init>(DisabledInitialContext.java:32)
	at io.quarkus.runtime.naming.DisabledInitialContextManager$1.getInitialContext(DisabledInitialContextManager.java:28)
	at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:730)
	at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:305)
	at javax.naming.InitialContext.init(InitialContext.java:236)
	at javax.naming.InitialContext.<init>(InitialContext.java:208)
	at javax.naming.directory.InitialDirContext.<init>(InitialDirContext.java:101)
	at org.jgroups.protocols.dns.DefaultDNSResolver.<init>(DefaultDNSResolver.java:42)
	at org.jgroups.protocols.dns.DNS_PING.init(DNS_PING.java:58)
	at org.jgroups.stack.ProtocolStack.initProtocolStack(ProtocolStack.java:794)
	at org.jgroups.stack.ProtocolStack.initProtocolStack(ProtocolStack.java:781)
	at org.jgroups.stack.ProtocolStack.init(ProtocolStack.java:777)
	at org.jgroups.JChannel.<init>(JChannel.java:155)
	at org.infinispan.remoting.transport.jgroups.EmbeddedJGroupsChannelConfigurator.createChannel(EmbeddedJGroupsChannelConfigurator.java:136)
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.channelFromConfigurator(JGroupsTransport.java:774)
	... 38 more

2022-10-18 10:49:36,656 WARN  [org.inf.CONTAINER] (main) ISPN000574: Global state cannot persisted because it is incomplete (usually caused by errors at startup).
2022-10-18 10:49:36,758 FATAL [org.inf.SERVER] (main) ISPN080028: Infinispan Server failed to start: org.infinispan.manager.EmbeddedCacheManagerStartupException: org.infinispan.commons.CacheConfigurationException: ISPN000541: Error while trying to create a channel using the specified configuration '[TCP(bundler.max_size=64000, sock_conn_timeout=300, thread_pool.keep_alive_time=60000, port_range=0, diag.enabled=false, bind_port=7800, thread_naming_pattern=pl, thread_pool.thread_dumps_threshold=10000, send_buf_size=640k, thread_pool.max_threads=200, bundler_type=transfer-queue, bind_addr=SITE_LOCAL, thread_pool.min_threads=0), RED(), MPING(ip_ttl=2, mcast_port=46655, mcast_addr=239.6.7.8, num_discovery_runs=3), MERGE3(max_interval=30000, min_interval=10000), FD_SOCK2(offset=50000), FD_ALL3(), VERIFY_SUSPECT2(timeout=1000), pbcast.NAKACK2(xmit_table_num_rows=50, use_mcast_xmit=false, xmit_table_msgs_per_row=1024, xmit_table_max_compaction_time=30000, xmit_interval=200, resend_last_seqno=true), UNICAST3(conn_close_timeout=5000, xmit_interval=200, xmit_table_num_rows=50, xmit_table_msgs_per_row=1024, xmit_table_max_compaction_time=30000), pbcast.STABLE(desired_avg_gossip=5000, max_bytes=1M), pbcast.GMS(join_timeout=2000, print_local_addr=false), UFC(min_threshold=0.40, max_credits=4m), MFC(min_threshold=0.40, max_credits=4m), FRAG4(frag_size=60000), dns.DNS_PING(dns_record_type=A, dns_query=test-base-functionality-ping.namespace-for-testing.svc.cluster.local)]'
	at org.infinispan.manager.DefaultCacheManager.internalStart(DefaultCacheManager.java:778)
	at org.infinispan.manager.DefaultCacheManager.start(DefaultCacheManager.java:742)
	at org.infinispan.server.SecurityActions.lambda$startCacheManager$1(SecurityActions.java:68)
	at org.infinispan.security.Security.doPrivileged(Security.java:56)
	at org.infinispan.server.SecurityActions.doPrivileged(SecurityActions.java:40)
	at org.infinispan.server.SecurityActions.startCacheManager(SecurityActions.java:71)
	at org.infinispan.server.Server.run(Server.java:408)
	at org.infinispan.server.Bootstrap.runInternal(Bootstrap.java:173)
	at org.infinispan.server.tool.Main.run(Main.java:98)
	at org.infinispan.server.Bootstrap.main(Bootstrap.java:56)
	at org.infininspan.quarkus.server.InfinispanQuarkusServer.run(InfinispanQuarkusServer.java:13)
	at org.infininspan.quarkus.server.InfinispanQuarkusServer_ClientProxy.run(Unknown Source)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:131)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:69)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
Caused by: org.infinispan.commons.CacheConfigurationException: ISPN000541: Error while trying to create a channel using the specified configuration '[TCP(bundler.max_size=64000, sock_conn_timeout=300, thread_pool.keep_alive_time=60000, port_range=0, diag.enabled=false, bind_port=7800, thread_naming_pattern=pl, thread_pool.thread_dumps_threshold=10000, send_buf_size=640k, thread_pool.max_threads=200, bundler_type=transfer-queue, bind_addr=SITE_LOCAL, thread_pool.min_threads=0), RED(), MPING(ip_ttl=2, mcast_port=46655, mcast_addr=239.6.7.8, num_discovery_runs=3), MERGE3(max_interval=30000, min_interval=10000), FD_SOCK2(offset=50000), FD_ALL3(), VERIFY_SUSPECT2(timeout=1000), pbcast.NAKACK2(xmit_table_num_rows=50, use_mcast_xmit=false, xmit_table_msgs_per_row=1024, xmit_table_max_compaction_time=30000, xmit_interval=200, resend_last_seqno=true), UNICAST3(conn_close_timeout=5000, xmit_interval=200, xmit_table_num_rows=50, xmit_table_msgs_per_row=1024, xmit_table_max_compaction_time=30000), pbcast.STABLE(desired_avg_gossip=5000, max_bytes=1M), pbcast.GMS(join_timeout=2000, print_local_addr=false), UFC(min_threshold=0.40, max_credits=4m), MFC(min_threshold=0.40, max_credits=4m), FRAG4(frag_size=60000), dns.DNS_PING(dns_record_type=A, dns_query=test-base-functionality-ping.namespace-for-testing.svc.cluster.local)]'
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.channelFromConfigurator(JGroupsTransport.java:776)
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.buildChannel(JGroupsTransport.java:745)
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.initChannel(JGroupsTransport.java:510)
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.start(JGroupsTransport.java:491)
	at org.infinispan.remoting.transport.jgroups.CorePackageImpl$1.start(CorePackageImpl.java:42)
	at org.infinispan.remoting.transport.jgroups.CorePackageImpl$1.start(CorePackageImpl.java:27)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.invokeStart(BasicComponentRegistryImpl.java:617)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:608)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:577)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:808)
	at org.infinispan.metrics.impl.MetricsCollector.start(MetricsCollector.java:76)
	at org.infinispan.metrics.impl.CorePackageImpl$1.start(CorePackageImpl.java:41)
	at org.infinispan.metrics.impl.CorePackageImpl$1.start(CorePackageImpl.java:34)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.invokeStart(BasicComponentRegistryImpl.java:617)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:608)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:577)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:808)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startDependencies(BasicComponentRegistryImpl.java:635)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:599)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:577)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:808)
	at org.infinispan.factories.AbstractComponentRegistry.internalStart(AbstractComponentRegistry.java:357)
	at org.infinispan.factories.AbstractComponentRegistry.start(AbstractComponentRegistry.java:250)
	at org.infinispan.manager.DefaultCacheManager.internalStart(DefaultCacheManager.java:774)
	... 15 more
Caused by: javax.naming.NamingException: JNDI has been disabled, enable it with quarkus.naming.enable-jndi=true
	at io.quarkus.runtime.naming.DisabledInitialContext.init(DisabledInitialContext.java:210)
	at javax.naming.InitialContext.<init>(InitialContext.java:208)
	at javax.naming.directory.InitialDirContext.<init>(InitialDirContext.java:101)
	at javax.naming.ldap.InitialLdapContext.<init>(InitialLdapContext.java:102)
	at io.quarkus.runtime.naming.DisabledInitialContext.<init>(DisabledInitialContext.java:32)
	at io.quarkus.runtime.naming.DisabledInitialContextManager$1.getInitialContext(DisabledInitialContextManager.java:28)
	at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:730)
	at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:305)
	at javax.naming.InitialContext.init(InitialContext.java:236)
	at javax.naming.InitialContext.<init>(InitialContext.java:208)
	at javax.naming.directory.InitialDirContext.<init>(InitialDirContext.java:101)
	at org.jgroups.protocols.dns.DefaultDNSResolver.<init>(DefaultDNSResolver.java:42)
	at org.jgroups.protocols.dns.DNS_PING.init(DNS_PING.java:58)
	at org.jgroups.stack.ProtocolStack.initProtocolStack(ProtocolStack.java:794)
	at org.jgroups.stack.ProtocolStack.initProtocolStack(ProtocolStack.java:781)
	at org.jgroups.stack.ProtocolStack.init(ProtocolStack.java:777)
	at org.jgroups.JChannel.<init>(JChannel.java:155)
	at org.infinispan.remoting.transport.jgroups.EmbeddedJGroupsChannelConfigurator.createChannel(EmbeddedJGroupsChannelConfigurator.java:136)
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.channelFromConfigurator(JGroupsTransport.java:774)
	... 38 more

2022-10-18 10:49:36,759 INFO  [io.quarkus] (main) infinispan-quarkus-server-runner stopped in 0.000s
```

Adding the `quarkus.naming.enable-jndi=true` option at build time could resolve the issue.

**Comment by ryanemerson** [comment]
[Enabling JNDI](https://github.com/ryanemerson/infinispan-quarkus/tree/enable_jndi) is not sufficient as we now get:

```java
2022-10-20 17:39:16,743 INFO  [io.quarkus] (main) infinispan-quarkus-server-runner 14.0.1.Final native (powered by Quarkus 2.13.0.Final) started in 0.017s. 
2022-10-20 17:39:16,744 INFO  [io.quarkus] (main) Profile prod activated. 
2022-10-20 17:39:16,744 INFO  [io.quarkus] (main) Installed features: [cdi, infinispan-embedded, infinispan-server]
2022-10-20 17:39:16,744 INFO  [BOOT] (main) JVM Substrate VM Oracle Corporation GraalVM 22.1.0 Java 11 CE
2022-10-20 17:39:16,745 INFO  [BOOT] (main) JVM arguments = [-Dinfinispan.server.home.path=/opt/infinispan, --bind-address=0.0.0.0, -l, /opt/infinispan/server/conf/operator/log4j.xml, -c, operator/infinispan-base.xml, -c, operator/infinispan-admin.xml]
2022-10-20 17:39:16,745 INFO  [BOOT] (main) PID = 40
2022-10-20 17:39:16,745 INFO  [org.inf.SERVER] (main) ISPN080000: Infinispan Server 14.0.1.Final starting
2022-10-20 17:39:16,745 INFO  [org.inf.SERVER] (main) ISPN080017: Server configuration: operator/infinispan-base.xml
2022-10-20 17:39:16,745 INFO  [org.inf.SERVER] (main) ISPN080017: Server configuration: operator/infinispan-admin.xml
2022-10-20 17:39:16,745 INFO  [org.inf.SERVER] (main) ISPN080032: Logging configuration: /opt/infinispan/server/conf/operator/log4j.xml
2022-10-20 17:39:16,755 WARN  [org.inf.SERVER] (main) ISPN080059: No script engines are available
2022-10-20 17:39:16,761 INFO  [org.inf.CONTAINER] (main) ISPN000556: Starting user marshaller 'org.infinispan.commons.marshall.ImmutableProtoStreamMarshaller'
2022-10-20 17:39:16,777 INFO  [org.inf.CLUSTER] (main) ISPN000078: Starting JGroups channel `test-base-functionality` with stack `image-tcp`
2022-10-20 17:39:16,784 ERROR [org.inf.CONFIG] (main) ISPN000660: DefaultCacheManager start failed, stopping any running components: org.infinispan.commons.CacheConfigurationException: ISPN000541: Error while trying to create a channel using the specified configuration '[TCP(bundler.max_size=64000, sock_conn_timeout=300, thread_pool.keep_alive_time=60000, port_range=0, diag.enabled=false, bind_port=7800, thread_naming_pattern=pl, thread_pool.thread_dumps_threshold=10000, send_buf_size=640k, thread_pool.max_threads=200, bundler_type=transfer-queue, bind_addr=SITE_LOCAL, thread_pool.min_threads=0), RED(), MPING(ip_ttl=2, mcast_port=46655, mcast_addr=239.6.7.8, num_discovery_runs=3), MERGE3(max_interval=30000, min_interval=10000), FD_SOCK2(offset=50000), FD_ALL3(), VERIFY_SUSPECT2(timeout=1000), pbcast.NAKACK2(xmit_table_num_rows=50, use_mcast_xmit=false, xmit_table_msgs_per_row=1024, xmit_table_max_compaction_time=30000, xmit_interval=200, resend_last_seqno=true), UNICAST3(conn_close_timeout=5000, xmit_interval=200, xmit_table_num_rows=50, xmit_table_msgs_per_row=1024, xmit_table_max_compaction_time=30000), pbcast.STABLE(desired_avg_gossip=5000, max_bytes=1M), pbcast.GMS(join_timeout=2000, print_local_addr=false), UFC(min_threshold=0.40, max_credits=4m), MFC(min_threshold=0.40, max_credits=4m), FRAG4(frag_size=60000), dns.DNS_PING(dns_record_type=A, dns_query=test-base-functionality-ping.namespace-for-testing.svc.cluster.local)]'
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.channelFromConfigurator(JGroupsTransport.java:776)
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.buildChannel(JGroupsTransport.java:745)
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.initChannel(JGroupsTransport.java:510)
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.start(JGroupsTransport.java:491)
	at org.infinispan.remoting.transport.jgroups.CorePackageImpl$1.start(CorePackageImpl.java:42)
	at org.infinispan.remoting.transport.jgroups.CorePackageImpl$1.start(CorePackageImpl.java:27)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.invokeStart(BasicComponentRegistryImpl.java:617)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:608)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:577)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:808)
	at org.infinispan.metrics.impl.MetricsCollector.start(MetricsCollector.java:76)
	at org.infinispan.metrics.impl.CorePackageImpl$1.start(CorePackageImpl.java:41)
	at org.infinispan.metrics.impl.CorePackageImpl$1.start(CorePackageImpl.java:34)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.invokeStart(BasicComponentRegistryImpl.java:617)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:608)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:577)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:808)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startDependencies(BasicComponentRegistryImpl.java:635)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:599)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:577)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:808)
	at org.infinispan.factories.AbstractComponentRegistry.internalStart(AbstractComponentRegistry.java:357)
	at org.infinispan.factories.AbstractComponentRegistry.start(AbstractComponentRegistry.java:250)
	at org.infinispan.manager.DefaultCacheManager.internalStart(DefaultCacheManager.java:774)
	at org.infinispan.manager.DefaultCacheManager.start(DefaultCacheManager.java:742)
	at org.infinispan.server.SecurityActions.lambda$startCacheManager$1(SecurityActions.java:68)
	at org.infinispan.security.Security.doPrivileged(Security.java:56)
	at org.infinispan.server.SecurityActions.doPrivileged(SecurityActions.java:40)
	at org.infinispan.server.SecurityActions.startCacheManager(SecurityActions.java:71)
	at org.infinispan.server.Server.run(Server.java:408)
	at org.infinispan.server.Bootstrap.runInternal(Bootstrap.java:173)
	at org.infinispan.server.tool.Main.run(Main.java:98)
	at org.infinispan.server.Bootstrap.main(Bootstrap.java:56)
	at org.infininspan.quarkus.server.InfinispanQuarkusServer.run(InfinispanQuarkusServer.java:13)
	at org.infininspan.quarkus.server.InfinispanQuarkusServer_ClientProxy.run(Unknown Source)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:131)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:69)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
Caused by: javax.naming.NoInitialContextException: Cannot instantiate class: com.sun.jndi.dns.DnsContextFactory [Root exception is java.lang.ClassNotFoundException: com.sun.jndi.dns.DnsContextFactory]
	at javax.naming.spi.NamingManager.getFactory(NamingManager.java:760)
	at javax.naming.spi.NamingManager.lambda$getInitialContext$1(NamingManager.java:722)
	at jdk.internal.loader.AbstractClassLoaderValue$Memoizer.get(AbstractClassLoaderValue.java:329)
	at jdk.internal.loader.AbstractClassLoaderValue.computeIfAbsent(AbstractClassLoaderValue.java:205)
	at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:722)
	at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:305)
	at javax.naming.InitialContext.init(InitialContext.java:236)
	at javax.naming.InitialContext.<init>(InitialContext.java:208)
	at javax.naming.directory.InitialDirContext.<init>(InitialDirContext.java:101)
	at org.jgroups.protocols.dns.DefaultDNSResolver.<init>(DefaultDNSResolver.java:42)
	at org.jgroups.protocols.dns.DNS_PING.init(DNS_PING.java:58)
	at org.jgroups.stack.ProtocolStack.initProtocolStack(ProtocolStack.java:794)
	at org.jgroups.stack.ProtocolStack.initProtocolStack(ProtocolStack.java:781)
	at org.jgroups.stack.ProtocolStack.init(ProtocolStack.java:777)
	at org.jgroups.JChannel.<init>(JChannel.java:155)
	at org.infinispan.remoting.transport.jgroups.EmbeddedJGroupsChannelConfigurator.createChannel(EmbeddedJGroupsChannelConfigurator.java:136)
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.channelFromConfigurator(JGroupsTransport.java:774)
	... 38 more
Caused by: java.lang.ClassNotFoundException: com.sun.jndi.dns.DnsContextFactory
	at java.lang.Class.forName(DynamicHub.java:1121)
	at com.sun.naming.internal.VersionHelper.loadClass(VersionHelper.java:127)
	at com.sun.naming.internal.VersionHelper.loadClass(VersionHelper.java:133)
	at com.sun.naming.internal.VersionHelper.loadClass(VersionHelper.java:96)
	at javax.naming.spi.NamingManager.getFactory(NamingManager.java:757)
	... 54 more
```
