### ISSUE TITLE
ClassNotFoundException: com.sun.jndi.dns.DnsContextFactory

### ISSUE THREAD

**Issue by ryanemerson** [infinispan/infinispan-quarkus#2]
The JGroups protocol `DNS_PING` throws a `ClassNotFoundException: com.sun.jndi.dns.DnsContextFactory`. This protocol is required for use in Kubernetes.

```java
2020-05-13 10:07:15,931 INFO  [io.quarkus] (main) config-generator 2.0.0.Dev01 (powered by Quarkus 1.4.1.Final) started in 0.013s. 
2020-05-13 10:07:15,931 INFO  [io.quarkus] (main) Profile prod activated. 
2020-05-13 10:07:15,931 INFO  [io.quarkus] (main) Installed features: [cdi, qute]
2020-05-13 10:07:16,183 INFO  [io.quarkus] (main) config-generator stopped in 0.000s
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2020-05-13 10:07:18,838 INFO  [ListenerBean] (main) The application is starting...
2020-05-13 10:07:18,972 INFO  [org.inf.CONTAINER] (main) ISPN000128: Infinispan version: Infinispan 'N/A' 11.0.0.Dev05
2020-05-13 10:07:18,973 INFO  [org.inf.CLUSTER] (main) ISPN000078: Starting JGroups channel infinispan
2020-05-13 10:07:18,983 WARN  [org.inf.CONTAINER] (main) ISPN000574: Global state cannot persisted because it is incomplete (usually caused by errors at startup).
2020-05-13 10:07:18,985 ERROR [ListenerBean] (main) Error encountered with server startup!: java.util.concurrent.CompletionException: org.infinispan.manager.EmbeddedCacheManagerStartupException: org.infinispan.commons.CacheConfigurationException: Unable to instantiate class com.sun.jndi.dns.DnsContextFactory
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:870)
        at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:883)
        at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2251)
        at org.infinispan.server.Server.run(Server.java:371)
        at org.infininspan.quarkus.server.ServerResource.onStart(ServerResource.java:27)
        at org.infininspan.quarkus.server.ServerResource_Observer_onStart_fd71b5e0b207b7d1ef838b94eaeff75e52b8f463.notify(ServerResource_Observer_onStart_fd71b5e0b207b7d1ef838b94eaeff75e52b8f463.zig:111)
        at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:282)
        at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:267)
        at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:69)
        at io.quarkus.arc.runtime.LifecycleEventRunner.fireStartupEvent(LifecycleEventRunner.java:23)
        at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:113)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent65.deploy_0(LifecycleEventsBuildStep$startupEvent65.zig:77)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent65.deploy(LifecycleEventsBuildStep$startupEvent65.zig:36)
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:170)
        at io.quarkus.runtime.Application.start(Application.java:90)
        at io.quarkus.runtime.Application.run(Application.java:228)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:41)
Caused by: org.infinispan.manager.EmbeddedCacheManagerStartupException: org.infinispan.commons.CacheConfigurationException: Unable to instantiate class com.sun.jndi.dns.DnsContextFactory
        at org.infinispan.manager.DefaultCacheManager.internalStart(DefaultCacheManager.java:769)
        at org.infinispan.manager.DefaultCacheManager.start(DefaultCacheManager.java:735)
        at org.infinispan.server.SecurityActions.lambda$startCacheManager$1(SecurityActions.java:64)
        at org.infinispan.security.Security.doPrivileged(Security.java:46)
        at org.infinispan.server.SecurityActions.doPrivileged(SecurityActions.java:36)
        at org.infinispan.server.SecurityActions.startCacheManager(SecurityActions.java:67)
        at org.infinispan.server.Server.run(Server.java:319)
        ... 13 more
Caused by: org.infinispan.commons.CacheConfigurationException: Unable to instantiate class com.sun.jndi.dns.DnsContextFactory
        at org.infinispan.commons.util.Util.loadClass(Util.java:139)
        at org.infinispan.commons.util.Util.getInstance(Util.java:23)
        at org.infinispan.server.context.ServerInitialContextFactoryBuilder.createInitialContextFactory(ServerInitialContextFactoryBuilder.java:33)
        at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:727)
        at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:305)
        at javax.naming.InitialContext.init(InitialContext.java:236)
        at javax.naming.InitialContext.<init>(InitialContext.java:208)
        at javax.naming.directory.InitialDirContext.<init>(InitialDirContext.java:101)
        at org.jgroups.protocols.dns.DefaultDNSResolver.<init>(DefaultDNSResolver.java:42)
        at org.jgroups.protocols.dns.DNS_PING.init(DNS_PING.java:55)
        at org.jgroups.stack.ProtocolStack.initProtocolStack(ProtocolStack.java:841)
        at org.jgroups.stack.ProtocolStack.setup(ProtocolStack.java:484)
        at org.jgroups.JChannel.init(JChannel.java:952)
        at org.jgroups.JChannel.<init>(JChannel.java:125)
        at org.infinispan.remoting.transport.jgroups.FileJGroupsChannelConfigurator.createChannel(FileJGroupsChannelConfigurator.java:49)
        at org.infinispan.remoting.transport.jgroups.JGroupsTransport.buildChannel(JGroupsTransport.java:608)
        at org.infinispan.remoting.transport.jgroups.JGroupsTransport.initChannel(JGroupsTransport.java:461)
        at org.infinispan.remoting.transport.jgroups.JGroupsTransport.start(JGroupsTransport.java:445)
        at org.infinispan.remoting.transport.jgroups.CorePackageImpl$1.start(CorePackageImpl.java:40)
        at org.infinispan.remoting.transport.jgroups.CorePackageImpl$1.start(CorePackageImpl.java:27)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.invokeStart(BasicComponentRegistryImpl.java:587)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:578)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:547)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.access$700(BasicComponentRegistryImpl.java:30)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:770)
        at org.infinispan.metrics.impl.MetricsCollector.start(MetricsCollector.java:69)
        at org.infinispan.metrics.impl.CorePackageImpl$1.start(CorePackageImpl.java:41)
        at org.infinispan.metrics.impl.CorePackageImpl$1.start(CorePackageImpl.java:34)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.invokeStart(BasicComponentRegistryImpl.java:587)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:578)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:547)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.access$700(BasicComponentRegistryImpl.java:30)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:770)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.startDependencies(BasicComponentRegistryImpl.java:605)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:569)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:547)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.access$700(BasicComponentRegistryImpl.java:30)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:770)
        at org.infinispan.factories.AbstractComponentRegistry.internalStart(AbstractComponentRegistry.java:341)
        at org.infinispan.factories.AbstractComponentRegistry.start(AbstractComponentRegistry.java:237)
        at org.infinispan.manager.DefaultCacheManager.internalStart(DefaultCacheManager.java:764)
        ... 19 more
Caused by: java.lang.ClassNotFoundException: com.sun.jndi.dns.DnsContextFactory
        at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:60)
        at java.lang.Class.forName(DynamicHub.java:1224)
        at org.infinispan.commons.util.Util.loadClassStrict(Util.java:187)
        at org.infinispan.commons.util.Util.loadClass(Util.java:137)
        ... 59 more
```

**Comment by wburns** [comment]
@ryanemerson do we set this in the environment via open shift? I wonder because we can't just support any implementation, it has to be done at compilation time. Do we want to only support the default one if none are provided and this implementation?
