### ISSUE TITLE
Clustered lock failures

### ISSUE THREAD

**Issue by ryanemerson** [infinispan/infinispan-quarkus#36]
If a server configuration has the `clustered-locks` element the following exception is thrown on startup:

```
2020-11-02 06:57:49,420 WARN [io.qua.qut.run.ContentTypes] (main) Unable to detect the content type for templates/jgroups-encrypt; using application/octet-stream
2020-11-02 06:57:49,421 INFO [io.quarkus] (main) config-generator 2.1.0.Dev05 native (powered by Quarkus 1.7.4.Final) started in 0.006s.
2020-11-02 06:57:49,421 INFO [io.quarkus] (main) Profile prod activated.
2020-11-02 06:57:49,421 INFO [io.quarkus] (main) Installed features: [cdi, qute]
2020-11-02 06:57:49,646 INFO [io.quarkus] (main) config-generator stopped in 0.000s
2020-11-02 06:57:49,665 ERROR [io.qua.application] (main) Failed to start application (with profile prod): java.lang.RuntimeException: Error injecting org.infinispan.server.Server org.infininspan.quarkus.server.ServerResource.server
at org.infininspan.quarkus.server.ServerResource_Bean.create(ServerResource_Bean.zig:148)
at org.infininspan.quarkus.server.ServerResource_Bean.get(ServerResource_Bean.zig:186)
at org.infininspan.quarkus.server.ServerResource_Bean.get(ServerResource_Bean.zig:221)
at org.infininspan.quarkus.server.ServerResource_Observer_onStart_fd71b5e0b207b7d1ef838b94eaeff75e52b8f463.notify(ServerResource_Observer_onStart_fd71b5e0b207b7d1ef838b94eaeff75e52b8f463.zig:100)
at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:282)
at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:267)
at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:69)
at io.quarkus.arc.runtime.LifecycleEventRunner.fireStartupEvent(LifecycleEventRunner.java:23)
at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:113)
at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent-858218658.deploy_0(LifecycleEventsBuildStep$startupEvent-858218658.zig:81)
at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent-858218658.deploy(LifecycleEventsBuildStep$startupEvent-858218658.zig:40)
at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:432)
at io.quarkus.runtime.Application.start(Application.java:90)
at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:91)
at io.quarkus.runtime.Quarkus.run(Quarkus.java:61)
at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
at io.quarkus.runtime.Quarkus.run(Quarkus.java:106)
at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
Caused by: org.infinispan.commons.CacheConfigurationException: Could not instantiate module configuration builder 'org.infinispan.lock.configuration.ClusteredLockManagerConfigurationBuilder'
at org.infinispan.configuration.global.GlobalConfigurationBuilder.addModule(GlobalConfigurationBuilder.java:220)
at org.infinispan.lock.configuration.ClusteredLockConfigurationParser.readElement(ClusteredLockConfigurationParser.java:47)
at org.infinispan.configuration.parsing.ParserRegistry.parseElement(ParserRegistry.java:224)
at org.infinispan.configuration.parsing.XMLExtendedStreamReaderImpl.handleAny(XMLExtendedStreamReaderImpl.java:60)
at org.infinispan.configuration.parsing.Parser.parseContainer(Parser.java:779)
at org.infinispan.configuration.parsing.Parser.readElement(Parser.java:118)
at org.infinispan.configuration.parsing.ParserRegistry.parseElement(ParserRegistry.java:224)
at org.infinispan.configuration.parsing.ParserRegistry.parse(ParserRegistry.java:194)
at org.infinispan.configuration.parsing.ParserRegistry.parse(ParserRegistry.java:180)
at org.infinispan.configuration.parsing.ParserRegistry.parse(ParserRegistry.java:169)
at org.infinispan.server.Server.parseConfiguration(Server.java:274)
at org.infinispan.server.Server.<init>(Server.java:202)
at org.infinispan.quarkus.server.runtime.InfinispanServerProducer.server(InfinispanServerProducer.java:49)
at org.infinispan.quarkus.server.runtime.InfinispanServerProducer_ProducerMethod_server_571276351519ba727e1410402ad4516addb1c6ca_Bean.create(InfinispanServerProducer_ProducerMethod_server_571276351519ba727e1410402ad4516addb1c6ca_Bean.zig:154)
at org.infinispan.quarkus.server.runtime.InfinispanServerProducer_ProducerMethod_server_571276351519ba727e1410402ad4516addb1c6ca_Bean.get(InfinispanServerProducer_ProducerMethod_server_571276351519ba727e1410402ad4516addb1c6ca_Bean.zig:184)
at org.infinispan.quarkus.server.runtime.InfinispanServerProducer_ProducerMethod_server_571276351519ba727e1410402ad4516addb1c6ca_Bean.get(InfinispanServerProducer_ProducerMethod_server_571276351519ba727e1410402ad4516addb1c6ca_Bean.zig:219)
at org.infininspan.quarkus.server.ServerResource_Bean.create(ServerResource_Bean.zig:131)
... 17 more
Caused by: java.lang.NoSuchMethodException: org.infinispan.lock.configuration.ClusteredLockManagerConfigurationBuilder.<init>(org.infinispan.configuration.global.GlobalConfigurationBuilder)
at java.lang.Class.getConstructor0(DynamicHub.java:3349)
at java.lang.Class.getDeclaredConstructor(DynamicHub.java:2553)
at org.infinispan.configuration.global.GlobalConfigurationBuilder.addModule(GlobalConfigurationBuilder.java:215)
... 33 more
```

**Comment by galderz** [comment]
@ryanemerson Looks like some reflection registration is missing?

**Comment by galderz** [comment]
Or service registration, depends what `addModule` calls.

**Comment by ryanemerson** [comment]
PR linked.
