### ISSUE TITLE
Error in native with Mandrel 20.3: Incompatible change of initialization policy for com.sun.jndi.dns.DnsClient

### ISSUE THREAD

**Issue by galderz** [infinispan/infinispan-quarkus#40]
Error building native server with Mandrel 20.3. Binary does seem to get build though, see [here](https://gist.github.com/galderz/6d81577ccc0e1191e30de5ceeb85ac53).

```bash
com.oracle.svm.core.util.UserError$UserException: Incompatible change of initialization policy for com.sun.jndi.dns.DnsClient: trying to change RUN_TIME from feature com.oracle.svm.hosted.jdk.JDKInitializationFeature.afterRegistration to RERUN Quarkus
	at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
	at com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insertRec(ClassInitializationConfiguration.java:99)
	at com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insertRec(ClassInitializationConfiguration.java:113)
	at com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insertRec(ClassInitializationConfiguration.java:113)
	at com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insertRec(ClassInitializationConfiguration.java:113)
	at com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insertRec(ClassInitializationConfiguration.java:113)
	at com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insertRec(ClassInitializationConfiguration.java:113)
	at com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insert(ClassInitializationConfiguration.java:64)
	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.rerunInitialization(ConfigurableClassInitialization.java:379)
	at io.quarkus.runner.AutoFeature.beforeAnalysis(AutoFeature.zig:1036)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$7(NativeImageGenerator.java:696)
	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:70)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:696)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:558)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:471)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
09:08:23,881 INFO  [org.jbo.threads] JBoss Threads version 3.1.1.Final
```

To reproduce, do the following:

1. Check out [qollider](https://github.com/galderz/qollider) repo and build it with maven and java 14, e.g. `mvn clean install`.

2. Install [JBang](https://github.com/jbangdev/jbang) and execute:

```bash
jbang -Dqollider.version=999-SNAPSHOT https://raw.githubusercontent.com/galderz/qollider/master/examples/infinispan_quarkus.java \
    --jdk https://github.com/openjdk/jdk11u-dev/commit/5ad383f7b802c9e8894e843a18acafd33569979f \
    --mandrel https://github.com/graalvm/mandrel/commit/2fc1ec0892574f14133c3796bf88448ccaaea28e \
    --infinispan https://github.com/wburns/infinispan/commit/8dce81940cfef3d18057158112610ddb9493172c \
    --quarkus https://github.com/galderz/quarkus/commit/c9741eafa7ee6b2f8b2919ba1869fcae2383a60c \
    --infinispan-quarkus https://github.com/galderz/infinispan-quarkus/commit/53ec46a4ed3ce4e9811296bde1fa28560114f7ce
```

This script will build JDK, Mandrel, Infinispan, Quarkus and Infinispan Quarkus projects, and then it produces 2 native servers: one with profiling and tracing and another a production one.

This issue should be assigned to @zakkak who's helping out with this.

**Comment by zakkak** [comment]
It looks like https://github.com/infinispan/infinispan-quarkus/blob/ba86fa9eebe89684a0c980044df8391ace91d19d/server/deployment/src/main/java/org/infinispan/quarkus/server/deployment/InfinispanServerProcessor.java#L71 is no longer needed since `DnsClient` is reinitialized by default in 20.3 (both Mandrel and GraalVM CE distributions) (see https://github.com/graalvm/mandrel/blob/2fc1ec0892574f14133c3796bf88448ccaaea28e/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/jdk/JDKInitializationFeature.java#L121 and https://github.com/oracle/graal/blob/e97ad6237638246ff555657ddf48976a03a53d2e/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/jdk/JDKInitializationFeature.java#L121 respectively) 

```diff
diff --git a/server/deployment/src/main/java/org/infinispan/quarkus/server/deployment/InfinispanServerProcessor.java b/server/deployment/src/main/java/org/infinispan/quarkus/server/deployment/InfinispanServerProcessor.java
index 7a50b2e..42bc62a 100644
--- a/server/deployment/src/main/java/org/infinispan/quarkus/server/deployment/InfinispanServerProcessor.java
+++ b/server/deployment/src/main/java/org/infinispan/quarkus/server/deployment/InfinispanServerProcessor.java
@@ -66,9 +66,11 @@ class InfinispanServerProcessor {
    }
 
    @BuildStep
-   void reinitializeAtRuntime(BuildProducer<RuntimeReinitializedClassBuildItem> runtimeReinitialized) {
-      // The class contains a SecureRandom which must be reinitialized at runtime
-      runtimeReinitialized.produce(new RuntimeReinitializedClassBuildItem(DnsClient.class.getName()));
+   void initializeAtRuntime(BuildProducer<RuntimeInitializedClassBuildItem> runtimeInitialized) {
+      // The class contains a SecureRandom which must be initialized at runtime.
+      // Only needed for compatibility with Mandrel and GraalVM CE < 20.3, versions >= 20.3 initialize the class at 
+      // runtime by default.
+      runtimeInitialized.produce(new RuntimeInitializedClassBuildItem(DnsClient.class.getName()));
    }
 
    @BuildStep
```

Removes the error while maintaining backwards compatibility with Mandrel/GraalVM <= 20.2
