### ISSUE TITLE
Windows Release Failing

### ISSUE THREAD

**Issue by ryanemerson** [infinispan/infinispan-quarkus#55]
Currently the windows release is failing with the following:

```
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Building native image from D:\a\infinispan-quarkus\infinispan-quarkus\cli\target\ispn-native-image-source-jar\ispn-cli.jar
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Running Quarkus native-image plugin on GraalVM Version 20.3.0 (Java Version 11.0.9+10-jvmci-20.3-b06)
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] C:\hostedtoolcache\windows\GraalVM\20.3.0-java11\x64\bin\native-image.cmd -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Duser.language=en -J-Dfile.encoding=UTF-8 --allow-incomplete-classpath -H:ResourceConfigurationFiles=D:\a\infinispan-quarkus\infinispan-quarkus\cli/src/main/native/cli_resources.json -H:ReflectionConfigurationFiles=D:\a\infinispan-quarkus\infinispan-quarkus\cli\target/cli_reflection.json,D:\a\infinispan-quarkus\infinispan-quarkus\cli\target/kube_reflection.json,D:\a\infinispan-quarkus\infinispan-quarkus\cli\target/batch_reflection.json,D:\a\infinispan-quarkus\infinispan-quarkus\cli/src/main/native/cli.json --initialize-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy\$BySpaceAndTime -H:+JNI -H:+AllowFoldMethods -jar ispn-cli.jar -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:-AddAllCharsets -H:EnableURLProtocols=http,https --enable-all-security-services -H:+UseServiceLoaderFeature -H:+TraceServiceLoaderFeature -H:+StackTrace ispn-cli
[ispn-cli:6728]    classlist:   8,415.24 ms,  0.96 GB
Fatal error:com.oracle.svm.core.util.VMError$HostedError: java.lang.reflect.InvocationTargetException
[ispn-cli:6728]        (cap):  21,983.79 ms,  0.96 GB
[ispn-cli:6728]        setup:  23,255.38 ms,  0.96 GB
	at com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:72)
	at com.oracle.svm.core.jdk.JavaNetSubstitutions.addURLStreamHandler(JavaNetSubstitutions.java:164)
	at com.oracle.svm.core.jdk.JavaNetFeature.duringSetup(JavaNetSubstitutions.java:101)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$setupNativeImage$12(NativeImageGenerator.java:882)
	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:70)
	at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:882)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:556)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:471)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.oracle.svm.core.jdk.JavaNetSubstitutions.addURLStreamHandler(JavaNetSubstitutions.java:157)
	... 12 more
Caused by: java.util.ServiceConfigurationError: java.net.spi.URLStreamHandlerProvider: Provider org.infinispan.commons.jdkspecific.ClasspathURLStreamHandlerProvider not found
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:588)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1211)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1220)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1264)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1299)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1384)
	at java.base/java.net.URL$1.getNext(URL.java:1289)
	at java.base/java.net.URL$1.hasNext(URL.java:1304)
	at java.base/java.net.URL$2.run(URL.java:1330)
	at java.base/java.net.URL$2.run(URL.java:1327)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.net.URL.lookupViaProviders(URL.java:1326)
	at java.base/java.net.URL.getURLStreamHandler(URL.java:1412)
	... 17 more
Error: Image build request failed with exit status 1
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Infinispan Quarkus - Parent pom 12.1.0.CR2:
[INFO] 
[INFO] Infinispan Quarkus - Parent pom .................... SUCCESS [ 15.650 s]
[INFO] Infinispan - Quarkus - CLI ......................... FAILURE [01:26 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:48 min
[INFO] Finished at: 2021-03-22T16:00:13Z
[INFO] ------------------------------------------------------------------------
Error:  Failed to execute goal io.quarkus:quarkus-maven-plugin:1.11.0.Final:native-image (default) on project infinispan-quarkus-cli: Failed to generate native image: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
Error: r]: Build step io.quarkus.deployment.pkg.steps.NativeImageBuildStep#build threw an exception: java.lang.RuntimeException: Failed to build native image
Error:  	at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:307)
Error:  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Error:  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Error:  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Error:  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
Error:  	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:972)
Error:  	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
Error:  	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
Error:  	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
Error:  	at java.base/java.lang.Thread.run(Thread.java:834)
Error:  	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Error:  Caused by: java.nio.file.NoSuchFileException: D:\a\infinispan-quarkus\infinispan-quarkus\cli\target\ispn-native-image-source-jar\ispn-cli.exe
Error:  	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
Error:  	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
Error:  	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
Error:  	at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:53)
Error:  	at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:38)
Error:  	at java.base/sun.nio.fs.WindowsFileSystemProvider.readAttributes(WindowsFileSystemProvider.java:198)
Error:  	at java.base/java.nio.file.Files.readAttributes(Files.java:1763)
Error:  	at java.base/java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:225)
Error:  	at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
Error:  	at java.base/java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:322)
Error:  	at java.base/java.nio.file.Files.walkFileTree(Files.java:2716)
Error:  	at io.quarkus.bootstrap.util.IoUtils.copy(IoUtils.java:126)
Error:  	at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:281)
Error:  	... 10 more
Error:  -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
Error:  
Error:  After correcting the problems, you can resume the build with the command
Error:    mvn <args> -rf :infinispan-quarkus-cli
Error: Process completed with exit code 1.
```

**Comment by dhermanson** [comment]
I just ran into this issue, not in quarkus, but using vertx. I was building a fat jar with the `com.github.johnrengelman.shadow` gradle plugin.

Long story short, that particular class, `org.infinispan.commons.jdkspecific.ClasspathURLStreamHandlerProvider` is a versioned service. So it's service entry is in `org.infinispan:infinispan-commons:<version>:META-INF/versions/11/org/infinispan/commons/jdkspecific/ClasspathURLStreamHandlerProvider`

If you pop open the `MANIFEST.MF` for the `org.infinispan:infinispan-commons` jar, you'll see that it has an entry for multi-release:
```
Multi-Release: true
```

This is needed in order for the serviceloader to load implementations based on the version currently executing java runtime.

So, the fix for me was to add `Multi-Release: true` to my generated manifest for my fat jar. Problem solved.

Not sure if that fixes this issue, but our symptoms were very similar.
