### ISSUE TITLE
Windows CLI fails in interactive mode

### ISSUE THREAD

**Issue by ryanemerson** [infinispan/infinispan-quarkus#84]
When utilising the CLI on windows in interactive mode, the following exception is thrown:

```
>infinispan-cli.exe
←[0;31mUnsatisfiedLinkError: org.fusesource.jansi.internal.Kernel32.GetStdHandle(I)J [symbol: Java_org_fusesource_jansi_internal_Kernel32_GetStdHandle or Java_org_fusesource_jansi_internal_Kernel32_GetStdHandle__I]←[0;39m
```

aesh relies on  jansi 1.18. Unfortunately, better support is only added in 2.4.0 which is backwards incompatible so upgrading  in aesh is non-trivial.

**Comment by joshdcu** [comment]
+1. Faced a similar error when using the current latest release binary ([`14.0.14.Final`](https://github.com/infinispan/infinispan-quarkus/releases/tag/14.0.14.Final)) via the `kubectl` plugin approach documented [here](https://infinispan.org/docs/infinispan-operator/main/operator.html#installing-native-cli-plugin)...

```
>kubectl infinispan --help
Exception in thread "main" java.lang.UnsatisfiedLinkError: org.fusesource.jansi.internal.Kernel32.GetStdHandle(I)J [symbol: Java_org_fusesource_jansi_internal_Kernel32_GetStdHandle or Java_org_fusesource_jansi_internal_Kernel32_GetStdHandle__I]
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.access.JNINativeLinkage.getOrFindEntryPoint(JNINativeLinkage.java:152)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.JNIGeneratedMethodSupport.nativeCallAddress(JNIGeneratedMethodSupport.java:53)
        at org.fusesource.jansi.internal.Kernel32.GetStdHandle(Kernel32.java)
        at org.aesh.readline.terminal.impl.WinSysTerminal.setVTMode(WinSysTerminal.java:141)
        at org.aesh.readline.terminal.impl.WinSysTerminal.<init>(WinSysTerminal.java:44)
        at org.aesh.readline.terminal.impl.WinSysTerminal.<init>(WinSysTerminal.java:40)
        at org.aesh.readline.terminal.TerminalBuilder.createWindowsTerminal(TerminalBuilder.java:148)
        at org.aesh.readline.terminal.TerminalBuilder.build(TerminalBuilder.java:117)
        at org.aesh.readline.tty.terminal.TerminalConnection.<init>(TerminalConnection.java:91)
        at org.aesh.readline.tty.terminal.TerminalConnection.<init>(TerminalConnection.java:100)
        at org.infinispan.cli.impl.CliShell.<init>(CliShell.java:13)
        at org.infinispan.cli.commands.CLI.main(CLI.java:402)
        at org.infinispan.cli.quarkus.CliQuarkus.main(CliQuarkus.java:16)
Error: exit status 1
