### ISSUE TITLE
EC Keys are not supported when using the native binary

### ISSUE THREAD

**Issue by agilob** [infinispan/infinispan-quarkus#87]
```
kubectl infinispan --help
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: EC Keys are not supported when using the native binary
 at org.infinispan.cli.commands.CLI.main(CLI.java:345)
 at org.infinispan.cli.commands.CLI.main(CLI.java:354)
 at org.infinispan.cli.commands.CLI.main(CLI.java:358)
 at org.infinispan.cli.quarkus.CliQuarkus.main(CliQuarkus.java:14)
Caused by: java.lang.RuntimeException: EC Keys are not supported when using the native binary
 at io.fabric8.kubernetes.client.internal.CertUtils.handleECKey(CertUtils.java:16)
 at io.fabric8.kubernetes.client.internal.CertUtils.loadKey(CertUtils.java:130)
 at io.fabric8.kubernetes.client.internal.CertUtils.createKeyStore(CertUtils.java:108)
 at io.fabric8.kubernetes.client.internal.CertUtils.createKeyStore(CertUtils.java:244)
 at io.fabric8.kubernetes.client.internal.SSLUtils.keyManagers(SSLUtils.java:128)
 at io.fabric8.kubernetes.client.internal.SSLUtils.keyManagers(SSLUtils.java:122)
 at io.fabric8.kubernetes.client.utils.HttpClientUtils.createHttpClient(HttpClientUtils.java:129)
 at io.fabric8.kubernetes.client.utils.HttpClientUtils.createHttpClient(HttpClientUtils.java:66)
 at io.fabric8.kubernetes.client.BaseClient.<init>(BaseClient.java:51)
 at io.fabric8.kubernetes.client.BaseClient.<init>(BaseClient.java:43)
 at io.fabric8.kubernetes.client.BaseKubernetesClient.<init>(BaseKubernetesClient.java:146)
 at io.fabric8.kubernetes.client.DefaultKubernetesClient.<init>(DefaultKubernetesClient.java:32)
 at org.infinispan.cli.impl.KubernetesContext.<init>(KubernetesContext.java:24)
 at org.infinispan.cli.commands.CLI.initialCommandRuntimeBuilder(CLI.java:315)
 at org.infinispan.cli.commands.CLI.main(CLI.java:341)
 ... 3 more
```

I'm getting this on `infinispan-cli-13.0.6.Final` and `infinispan-cli-14.0.0.Dev01` I'm on linux

**Comment by tristantarrant** [comment]
I've opened an issue https://github.com/fabric8io/kubernetes-client/issues/3952

**Comment by manusa** [comment]
This is probably also related to: https://github.com/quarkusio/quarkus/pull/21849

**Comment by larsw** [comment]
I'm experiencing the same thing.

```
$ kubectl infinispan
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: EC Keys are not supported when using the native binary, please add the org.bouncycastle:bcpkix-jdk18on dependency
	at org.infinispan.cli.commands.CLI.main(CLI.java:382)
	at org.infinispan.cli.commands.CLI.main(CLI.java:391)
	at org.infinispan.cli.commands.CLI.main(CLI.java:404)
	at org.infinispan.cli.quarkus.CliQuarkus.main(CliQuarkus.java:16)
Caused by: java.lang.RuntimeException: EC Keys are not supported when using the native binary, please add the org.bouncycastle:bcpkix-jdk18on dependency
	at io.fabric8.kubernetes.client.internal.CertUtils.handleECKey(CertUtils.java:15)
	at io.fabric8.kubernetes.client.internal.CertUtils.loadKey(CertUtils.java:140)
	at io.fabric8.kubernetes.client.internal.CertUtils.createKeyStore(CertUtils.java:116)
	at io.fabric8.kubernetes.client.internal.CertUtils.createKeyStore(CertUtils.java:251)
	at io.fabric8.kubernetes.client.internal.SSLUtils.keyManagers(SSLUtils.java:168)
	at io.fabric8.kubernetes.client.internal.SSLUtils.keyManagers(SSLUtils.java:157)
	at io.fabric8.kubernetes.client.utils.HttpClientUtils.applyCommonConfiguration(HttpClientUtils.java:207)
	at io.fabric8.kubernetes.client.okhttp.OkHttpClientFactory.newBuilder(OkHttpClientFactory.java:94)
	at io.fabric8.kubernetes.client.okhttp.OkHttpClientFactory.newBuilder(OkHttpClientFactory.java:31)
	at io.fabric8.kubernetes.client.utils.HttpClientUtils.createHttpClient(HttpClientUtils.java:146)
	at io.fabric8.kubernetes.client.DefaultKubernetesClient.<init>(DefaultKubernetesClient.java:56)
	at io.fabric8.kubernetes.client.DefaultKubernetesClient.<init>(DefaultKubernetesClient.java:48)
	at org.infinispan.cli.impl.KubernetesContext.<init>(KubernetesContext.java:24)
	at org.infinispan.cli.commands.CLI.initialCommandRuntimeBuilder(CLI.java:353)
	at org.infinispan.cli.commands.CLI.main(CLI.java:379)
	... 3 more
```

**Comment by ryanemerson** [comment]
@larsw What version of Infinispan are you using? This should have been resolved when we upgraded to Quarkus `2.6.0.Final` https://github.com/quarkusio/quarkus/pull/21849.

**Comment by larsw** [comment]
Latest - 14.0.20.Final

Weird thing is, it only fails when I rename it and move it to/usr/local/bin
as the doc prescribes.

If I run it in a local directory (not via kubectl infinispan) it behaves
like the normal infinispan CLI

**Comment by stephankoelle** [comment]
using `ln -s infinispan-cli kubectl-infinispan` instead of renaming might be a solution
