### ISSUE TITLE
Native CLI fails to start with 14.0.0.Dev03

### ISSUE THREAD

**Issue by ryanemerson** [infinispan/infinispan-quarkus#98]
```
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: Could not instantiate class: class org.infinispan.cli.commands.CLI, no access to constructors.
    at org.infinispan.cli.commands.CLI.main(CLI.java:347)
    at org.infinispan.cli.commands.CLI.main(CLI.java:356)
    at org.infinispan.cli.commands.CLI.main(CLI.java:360)
    at org.infinispan.cli.quarkus.CliQuarkus.main(CliQuarkus.java:14)
Caused by: java.lang.RuntimeException: Could not instantiate class: class org.infinispan.cli.commands.CLI, no access to constructors.
    at org.aesh.util.ReflectionUtil.newInstance(ReflectionUtil.java:48)
    at org.aesh.command.impl.container.AeshCommandContainerBuilder.create(AeshCommandContainerBuilder.java:73)
    at org.aesh.command.impl.registry.MutableCommandRegistryImpl.addCommand(MutableCommandRegistryImpl.java:133)
    at org.aesh.command.impl.registry.AeshCommandRegistryBuilder.command(AeshCommandRegistryBuilder.java:57)
    at org.infinispan.cli.commands.CLI.initialCommandRuntimeBuilder(CLI.java:321)
    at org.infinispan.cli.commands.CLI.main(CLI.java:343)
```

This is caused by https://github.com/infinispan/infinispan/pull/10184 which changed the signature of `CLI#main` so that it throws an `IOException`.

**Comment by ryanemerson** [comment]
Bizarrely this only occurs when the native cli is built with the `maven-assembly-plugin` on the classpath as part of the package phase. Creating the zip using a different module works around the issue.
